import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./background.scss";
import KeyPressListener from "@/components/KeyPressListener";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <KeyPressListener></KeyPressListener>
        <div className="base"></div>
        <div className="background gradient"></div>
        {children}
      </body>
    </html>
  );
}
